// src/main/frontend/angular/src/pages/search.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import { HeaderComponent } from '../components/header/header.component';
import { FooterComponent } from '../components/footer/footer.component';
import { SearchFlightsComponent } from '../components/search-flights/search-flights.component';
import { FlightResultsTwoColumnsComponent } from '../components/flight-results-two-columns/flight-results-two-columns.component';

@Component({
  selector: 'app-search',
  standalone: true,
  imports: [CommonModule, HeaderComponent, FooterComponent, SearchFlightsComponent, FlightResultsTwoColumnsComponent],
  template: `
    <app-header></app-header>
    <div class="min-vh-100">
      <!-- SearchFlightsComponent должен иметь Output (onSearch) для передачи параметров поиска -->
      <app-search-flights (onSearch)="handleSearch($event)"></app-search-flights>
      <p *ngIf="loading">Загрузка...</p>
      <p *ngIf="error" style="color: red;">Ошибка: {{ error }}</p>
      <ng-container *ngIf="flights">
        <app-flight-results-two-columns [flightsData]="flights"></app-flight-results-two-columns>
      </ng-container>
    </div>
    <app-footer></app-footer>
  `
})
export class SearchComponent implements OnInit {
  flights: any = null;
  loading: boolean = false;
  error: string | null = null;

  constructor(private route: ActivatedRoute) {}

  ngOnInit() {
    // При изменении query-параметров (например, airportCode) выполняется поиск
    this.route.queryParams.subscribe(params => {
      const airportCode = params['airportCode'];
      if (airportCode) {
        this.handleSearch({ airportCode });
      }
    });
  }

  async handleSearch(searchParams: any) {
    this.loading = true;
    this.error = null;
    try {
      const response = await fetch('/api/flights/search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(searchParams)
      });
      if (!response.ok) {
        throw new Error('Ошибка при поиске рейсов');
      }
      this.flights = await response.json();
    } catch (err: any) {
      this.error = err.message;
    } finally {
      this.loading = false;
    }
  }
}

// src/main/frontend/react/src/pages/Search.jsx
import React, { useState, useEffect } from 'react';
import SearchFlightsComponent from '../components/SearchFlightsComponent';
import FlightResultsTwoColumnsComponent from '../components/FlightResultsTwoColumnsComponent';
import { useSearchParams } from 'react-router-dom';
import Header from '../components/Header';
import Footer from '../components/Footer';

const Search = () => {
  const [flights, setFlights] = useState(null); // Ожидается объект { departures: [...], arrivals: [...] }
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [urlParams, setUrlParams] = useSearchParams();

  const handleSearch = async (searchParams) => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch('/api/flights/search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(searchParams)
      });
      if (!response.ok) {
        throw new Error('Ошибка при поиске рейсов');
      }
      const data = await response.json();
      setFlights(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const airportCode = urlParams.get('airportCode');
    if (airportCode) {
      handleSearch({ airportCode: airportCode });
    }
  }, [urlParams]);

  return (
    <>
      <Header />
      <div class="min-vh-100">
        <SearchFlightsComponent onSearch={handleSearch} />
        {loading && <p>Загрузка...</p>}
        {error && <p style={{ color: 'red' }}>Ошибка: {error}</p>}
        {flights && <FlightResultsTwoColumnsComponent flightsData={flights} />}
      </div>
      <Footer />
    </>
  );
};

export default Search;
