// src/main/frontend/angular/src/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterModule, CommonModule], // <-- Добавляем необходимые модули
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  isAuthenticated = false;

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.checkAuthStatus();
  }

  private checkAuthStatus() {
    fetch('/api/auth/status', { credentials: 'include' })
      .then(response => response.json())
      .then(data => {
        this.isAuthenticated = data.authenticated;
      })
      .catch(error => console.error('Ошибка проверки авторизации:', error));
  }

  handleLogout() {
    fetch('/api/auth/logout', { method: 'POST', credentials: 'include' })
      .then(() => {
        this.isAuthenticated = false;
        this.router.navigate(['/']); // Возвращаем навигацию на главную
      })
      .catch(error => console.error('Ошибка при выходе:', error));
  }
}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" routerLink="/">FlyAway Sales</a>
  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" routerLink="/search">Поиск рейсов</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/airports">Карта аэропортов</a>
          </li>
          <ng-container *ngIf="isAuthenticated; else notAuth">
            <li class="nav-item">
              <a class="nav-link" routerLink="/profile">Личный кабинет</a>
            </li>
            <li class="nav-item">
              <button class="btn btn-danger nav-link" (click)="handleLogout()">Выход</button>
            </li>
          </ng-container>
          <ng-template #notAuth>
            <li class="nav-item">
              <a class="nav-link" routerLink="/login">Вход</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" routerLink="/register">Регистрация</a>
            </li>
          </ng-template>
        </ul>
      </div>
    </div>
  </nav>

// src/main/frontend/react/src/components/Header.jsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import 'bootstrap/dist/css/bootstrap.min.css';

const Header = () => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    fetch('/api/auth/status', { credentials: 'include' })
      .then(response => response.json())
      .then(data => {
        setIsAuthenticated(data.authenticated);
        console.log(data.authenticated);
      })
      .catch(error => console.error('Ошибка проверки авторизации:', error));
  }, []);

  const handleLogout = async () => {
    await fetch('/api/auth/logout', { method: 'POST', credentials: 'include' });
    setIsAuthenticated(false);
  };

  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <div className="container">
        <Link className="navbar-brand" to="/">FlyAway Sales</Link>

        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse" id="navbarNav">
          <ul className="navbar-nav ms-auto">
            <li className="nav-item">
              <Link className="nav-link" to="/search">Поиск рейсов</Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to="/airports">Карта аэропортов</Link>
            </li>
            {isAuthenticated ? (
              <>
                <li className="nav-item">
                  <Link className="nav-link" to="/profile">Личный кабинет</Link>
                </li>
                <li className="nav-item">
                  <button className="btn btn-danger nav-link" onClick={handleLogout}>Выход</button>
                </li>
              </>
            ) : (
              <>
                <li className="nav-item">
                  <Link className="nav-link" to="/login">Вход</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" to="/register">Регистрация</Link>
                </li>
              </>
            )}
          </ul>
        </div>
      </div>
    </nav>
  );
};

export default Header;
