// src/main/frontend/react/src/components/SearchFlightsComponent.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import 'bootstrap/dist/css/bootstrap.min.css';

const SearchFlightsComponent = ({ onSearch }) => {
  const [city, setCity] = useState('');
  const [airportCode, setAirportCode] = useState('');
  const [airportData, setAirportData] = useState([]);
  const [airportOptions, setAirportOptions] = useState([]);
  const [citySuggestions, setCitySuggestions] = useState([]);

  const navigate = useNavigate();
  const location = useLocation();


  useEffect(() => {
    const fetchAirports = async () => {
      try {
        const response = await fetch('/api/airports');
        if (!response.ok) {
          throw new Error('Ошибка при получении данных аэропортов');
        }
        const data = await response.json();
        setAirportData(data);
      } catch (err) {
        console.error(err);
      }
    };

    fetchAirports();
  }, []);

  const allCities = [...new Set(airportData.map(item => item.city))];

  const handleCityChange = (e) => {
    const value = e.target.value;
    setCity(value);
    const suggestions = allCities.filter(c =>
      c.toLowerCase().includes(value.toLowerCase())
    );
    setCitySuggestions(suggestions);
    if (allCities.includes(value)) {
      const options = airportData.filter(item => item.city === value);
      setAirportOptions(options);
    } else {
      setAirportOptions([]);
    }
    setAirportCode('');
  };

  const handleSuggestionClick = (suggestion) => {
    setCity(suggestion);
    setCitySuggestions([]);
    const options = airportData.filter(item => item.city === suggestion);
    setAirportOptions(options);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!airportCode) {
      alert("Пожалуйста, выберите аэропорт из списка после выбора города.");
      return;
    }
    
    const searchParams = new URLSearchParams(location.search);
    searchParams.set('airportCode', airportCode);
    navigate({
      pathname: location.pathname,
      search: searchParams.toString()
    });
  };


  return (
    <main className="search-main">
      <div className="container py-2 search-container">
        <h2 className="mb-4">Поиск рейсов</h2>
        <form onSubmit={handleSubmit}>
          <div className="mb-3 position-relative">
            <label htmlFor="city" className="form-label">Город</label>
            <input
              type="text"
              className="form-control"
              id="city"
              placeholder="Введите город"
              required
              value={city}
              onChange={handleCityChange}
            />
            {citySuggestions.length > 0 && (
              <ul className="list-group position-absolute suggestions-list">
                {citySuggestions.map((suggestion, index) => (
                  <li
                    key={index}
                    className="list-group-item list-group-item-action"
                    onClick={() => handleSuggestionClick(suggestion)}
                    style={{ cursor: 'pointer' }}
                  >
                    {suggestion}
                  </li>
                ))}
              </ul>
            )}
          </div>
          <div className="mb-3">
            <label htmlFor="airport" className="form-label">Аэропорт</label>
            <select
              className="form-select"
              id="airport"
              required
              value={airportCode}
              onChange={(e) => {setAirportCode(e.target.value); console.log(e.target.value)}}
            >
              <option value="">Выберите аэропорт</option>
              {airportOptions.map((item, index) => (
                <option key={index} value={item.airportCode}>
                  {item.airportCode} - {item.airportName}
                </option>
              ))}
            </select>
          </div>
          <button type="submit" className="btn btn-primary">Найти рейсы</button>
        </form>
      </div>
    </main>
  );
};

export default SearchFlightsComponent;

// src/main/frontend/angular/src/components/search-flights/search-flights.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import 'bootstrap/dist/css/bootstrap.min.css';

interface Airport {
  city: string;
  airportCode: string;
  airportName: string;
}

@Component({
  selector: 'app-search-flights',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './search-flights.component.html',
  styleUrls: ['./search-flights.component.css']
})
export class SearchFlightsComponent implements OnInit {
  city: string = '';
  airportCode: string = '';
  airportData: Airport[] = [];
  airportOptions: Airport[] = [];
  citySuggestions: string[] = [];

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit(): void {
    this.fetchAirports();
    this.route.queryParams.subscribe(params => {
      if (params['airportCode']) {
        this.airportCode = params['airportCode'];
      }
    });
  }

  async fetchAirports() {
    try {
      const response = await fetch('/api/airports');
      if (!response.ok) {
        throw new Error('Ошибка при получении данных аэропортов');
      }
      const data = await response.json();
      this.airportData = data;
      this.cdr.detectChanges();
    } catch (err) {
      console.error(err);
    }
  }

  get allCities(): string[] {
    return [...new Set(this.airportData.map(item => item.city))];
  }

  handleCityChange(event: any) {
    const value = event.target.value;
    this.city = value;
    this.citySuggestions = this.allCities.filter(c =>
      c.toLowerCase().includes(value.toLowerCase())
    );
    
    this.airportOptions = this.allCities.includes(value) 
      ? this.airportData.filter(item => item.city === value)
      : [];
    
    this.airportCode = '';
    this.cdr.detectChanges();
  }

  handleSuggestionClick(suggestion: string) {
    this.city = suggestion;
    this.citySuggestions = [];
    this.airportOptions = this.airportData.filter(item => item.city === suggestion);
    this.cdr.detectChanges();
  }

  handleSubmit(event: Event) {
    event.preventDefault();
    if (!this.airportCode) {
      alert("Пожалуйста, выберите аэропорт из списка после выбора города.");
      return;
    }
    this.router.navigate([], { 
      queryParams: { airportCode: this.airportCode },
      queryParamsHandling: 'merge'
    });
  }

  trackByCity(index: number, item: string): string {
    return item;
  }

  trackByAirport(index: number, item: Airport): string {
    return item.airportCode;
  }
}
<main class="search-main">
  <div class="container py-2 search-container">
    <h2 class="mb-4">Поиск рейсов</h2>
    <form (submit)="handleSubmit($event)">
      <div class="mb-3 position-relative">
        <label for="city" class="form-label">Город</label>
        <input
          type="text"
          class="form-control"
          id="city"
          placeholder="Введите город"
          required
          [value]="city"
          (input)="handleCityChange($event)"
        >
        <ul *ngIf="citySuggestions.length > 0" class="list-group position-absolute suggestions-list">
          <li 
            *ngFor="let suggestion of citySuggestions; trackBy: trackByCity"
            class="list-group-item list-group-item-action"
            (click)="handleSuggestionClick(suggestion)"
            style="cursor: pointer;"
          >
            {{ suggestion }}
          </li>
        </ul>
      </div>
      <div class="mb-3">
        <label for="airport" class="form-label">Аэропорт</label>
        <select
          class="form-select"
          id="airport"
          required
          [(ngModel)]="airportCode"
          name="airportCode"
          [disabled]="airportOptions.length === 0"
        >
          <option value="">Выберите аэропорт</option>
          <option 
            *ngFor="let item of airportOptions; trackBy: trackByAirport"
            [value]="item.airportCode"
          >
            {{ item.airportCode }} - {{ item.airportName }}
          </option>
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Найти рейсы</button>
    </form>
  </div>
</main>
