// src/main/frontend/react/src/pages/Airports.jsx
import React, { useEffect, useState } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import AirportsMap from '../components/AirportsMap';
import Header from '../components/Header';
import Footer from '../components/Footer';

const Airports = () => {
  const [airports, setAirports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchAirports = async () => {
      setLoading(true);
      try {
        const response = await fetch('/api/airports');
        if (!response.ok) {
          throw new Error('Ошибка при получении данных аэропортов');
        }
        const data = await response.json();
        setAirports(data);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchAirports();
  }, []);

  return (
    <>
      <Header />
      <AirportsMap />
      <div className="container mt-4 min-vh-100">
      <h2>Список аэропортов</h2>
      {loading && <p>Загрузка...</p>}
      {error && <p style={{ color: 'red' }}>Ошибка: {error}</p>}
      {airports.length > 0 ? (
          <table className="table table-striped">
          <thead>
              <tr>
              <th>Код аэропорта</th>
              <th>Название</th>
              <th>Город</th>
              <th>Координаты</th>
              <th>Часовой пояс</th>
              </tr>
          </thead>
          <tbody>
              {airports.map((airport) => (
              <tr key={airport.airportCode}>
                  <td>{airport.airportCode}</td>
                  <td>{airport.airportName}</td>
                  <td>{airport.city}</td>
                  <td>{airport.coordinates}</td>
                  <td>{airport.timezone}</td>
              </tr>
              ))}
          </tbody>
          </table>
      ) : (
          !loading && <p>Аэропорты не найдены.</p>
      )}
      </div>
      <Footer />
    </>
  );
};

export default Airports;

// src/main/frontend/angular/src/pages/airports.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HeaderComponent } from '../components/header/header.component';
import { AirportsMapComponent } from '../components/airports-map/airports-map.component';
import { FooterComponent } from '../components/footer/footer.component';

@Component({
  selector: 'app-airports',
  standalone: true,
  imports: [CommonModule, HeaderComponent, AirportsMapComponent, FooterComponent],
  template: `
    <app-header></app-header>
    <app-airports-map></app-airports-map>
    <div class="container mt-4 min-vh-100">
      <h2>Список аэропортов</h2>
      <p *ngIf="loading">Загрузка...</p>
      <p *ngIf="error" style="color: red;">Ошибка: {{ error }}</p>
      <ng-container *ngIf="airports.length > 0; else noAirports">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Код аэропорта</th>
              <th>Название</th>
              <th>Город</th>
              <th>Координаты</th>
              <th>Часовой пояс</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let airport of airports">
              <td>{{ airport.airportCode }}</td>
              <td>{{ airport.airportName }}</td>
              <td>{{ airport.city }}</td>
              <td>{{ airport.coordinates }}</td>
              <td>{{ airport.timezone }}</td>
            </tr>
          </tbody>
        </table>
      </ng-container>
      <ng-template #noAirports>
        <p *ngIf="!loading">Аэропорты не найдены.</p>
      </ng-template>
    </div>
    <app-footer></app-footer>
  `
})
export class AirportsComponent implements OnInit {
  airports: any[] = [];
  loading: boolean = false;
  error: string | null = null;

  async ngOnInit() {
    this.loading = true;
    try {
      const response = await fetch('/api/airports');
      if (!response.ok) {
        throw new Error('Ошибка при получении данных аэропортов');
      }
      this.airports = await response.json();
    } catch (err: any) {
      this.error = err.message;
    } finally {
      this.loading = false;
    }
  }
}
