// src/main/frontend/react/src/components/FlightResultsTwoColumnsComponent.jsx
import React, { useState } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import { useNavigate } from 'react-router-dom';

const statusOptions = [
  'All', 'Scheduled', 'On Time', 'Delayed', 'Departed', 'Arrived', 'Cancelled'
];

const FlightResultsTwoColumnsComponent = ({ flightsData }) => {
  const navigate = useNavigate();
  const [depSortOrder, setDepSortOrder] = useState('asc'); // Сортировка по времени отправления
  const [depStatusFilter, setDepStatusFilter] = useState('All');

  const [arrSortOrder, setArrSortOrder] = useState('asc'); // Сортировка по времени прибытия
  const [arrStatusFilter, setArrStatusFilter] = useState('All');

  const filteredDepartures = flightsData.departures
    .filter(flight => depStatusFilter === 'All' || flight.status === depStatusFilter)
    .sort((a, b) => {
      const timeA = new Date(a.scheduledDeparture).getTime();
      const timeB = new Date(b.scheduledDeparture).getTime();
      return depSortOrder === 'asc' ? timeA - timeB : timeB - timeA;
    });

  const filteredArrivals = flightsData.arrivals
    .filter(flight => arrStatusFilter === 'All' || flight.status === arrStatusFilter)
    .sort((a, b) => {
      const timeA = new Date(a.scheduledArrival).getTime();
      const timeB = new Date(b.scheduledArrival).getTime();
      return arrSortOrder === 'asc' ? timeA - timeB : timeB - timeA;
    });

  return (
    <div className="container mt-5">
      <div className="row">
        {/* Колонка "Отправление" */}
        <div className="col-md-6">
          <h2>Отправление</h2>
          <div className="d-flex mb-2">
            <div className="me-2">
              <label>Сортировать по времени:</label>
              <select
                className="form-select"
                value={depSortOrder}
                onChange={(e) => setDepSortOrder(e.target.value)}
              >
                <option value="asc">По возрастанию</option>
                <option value="desc">По убыванию</option>
              </select>
            </div>
            <div>
              <label>Фильтр по статусу:</label>
              <select
                className="form-select"
                value={depStatusFilter}
                onChange={(e) => setDepStatusFilter(e.target.value)}
              >
                {statusOptions.map((status, idx) => (
                  <option key={idx} value={status}>{status}</option>
                ))}
              </select>
            </div>
          </div>
          {filteredDepartures.length === 0 ? (
            <p>Рейсы не найдены.</p>
          ) : (
            <table className="table table-striped table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Номер рейса</th>
                  <th>Время вылета</th>
                  <th>Статус</th>
                </tr>
              </thead>
              <tbody>
                {filteredDepartures.map((flight) => (
                  <tr
                    key={flight.flightId}
                    style={{ cursor: 'pointer' }}
                    onClick={() => navigate(`/flight/${flight.flightId}`)}
                  >
                    <td>{flight.flightId}</td>
                    <td>{flight.flightNo}</td>
                    <td>{new Date(flight.scheduledDeparture).toLocaleString()}</td>
                    <td>{flight.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        {/* Колонка "Прибытие" */}
        <div className="col-md-6">
          <h2>Прибытие</h2>
          <div className="d-flex mb-2">
            <div className="me-2">
              <label>Сортировать по времени:</label>
              <select
                className="form-select"
                value={arrSortOrder}
                onChange={(e) => setArrSortOrder(e.target.value)}
              >
                <option value="asc">По возрастанию</option>
                <option value="desc">По убыванию</option>
              </select>
            </div>
            <div>
              <label>Фильтр по статусу:</label>
              <select
                className="form-select"
                value={arrStatusFilter}
                onChange={(e) => setArrStatusFilter(e.target.value)}
              >
                {statusOptions.map((status, idx) => (
                  <option key={idx} value={status}>{status}</option>
                ))}
              </select>
            </div>
          </div>
          {filteredArrivals.length === 0 ? (
            <p>Рейсы не найдены.</p>
          ) : (
            <table className="table table-striped table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Номер рейса</th>
                  <th>Время прибытия</th>
                  <th>Статус</th>
                </tr>
              </thead>
              <tbody>
                {filteredArrivals.map((flight) => (
                  <tr
                    key={flight.flightId}
                    style={{ cursor: 'pointer' }}
                    onClick={() => navigate(`/flight/${flight.flightId}`)}
                  >
                    <td>{flight.flightId}</td>
                    <td>{flight.flightNo}</td>
                    <td>{new Date(flight.scheduledArrival).toLocaleString()}</td>
                    <td>{flight.status}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  );
};

export default FlightResultsTwoColumnsComponent;

// src/main/frontend/angular/src/components/flight-results-two-columns/flight-results-two-columns.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import 'bootstrap/dist/css/bootstrap.min.css';

interface Flight {
  flightId: number | string;
  flightNo: string;
  scheduledDeparture: string;
  scheduledArrival: string;
  status: string;
}

interface FlightsData {
  departures: Flight[];
  arrivals: Flight[];
}

@Component({
  selector: 'app-flight-results-two-columns',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './flight-results-two-columns.component.html'
})
export class FlightResultsTwoColumnsComponent {
  @Input() flightsData!: FlightsData;

  statusOptions = ['All', 'Scheduled', 'On Time', 'Delayed', 'Departed', 'Arrived', 'Cancelled'];

  depSortOrder: 'asc' | 'desc' = 'asc';
  depStatusFilter: string = 'All';

  arrSortOrder: 'asc' | 'desc' = 'asc';
  arrStatusFilter: string = 'All';

  constructor(private router: Router) {}

  get filteredDepartures() {
    if (!this.flightsData?.departures) return [];
    return this.flightsData.departures
      .filter(flight => this.depStatusFilter === 'All' || flight.status === this.depStatusFilter)
      .sort((a, b) => {
        const timeA = new Date(a.scheduledDeparture).getTime();
        const timeB = new Date(b.scheduledDeparture).getTime();
        return this.depSortOrder === 'asc' ? timeA - timeB : timeB - timeA;
      });
  }

  get filteredArrivals() {
    if (!this.flightsData?.arrivals) return [];
    return this.flightsData.arrivals
      .filter(flight => this.arrStatusFilter === 'All' || flight.status === this.arrStatusFilter)
      .sort((a, b) => {
        const timeA = new Date(a.scheduledArrival).getTime();
        const timeB = new Date(b.scheduledArrival).getTime();
        return this.arrSortOrder === 'asc' ? timeA - timeB : timeB - timeA;
      });
  }

  navigateToFlight(flightId: number | string) {
    this.router.navigate(['/flight', flightId]);
  }
}

<div class="container mt-5">
    <div class="row">
      <!-- Колонка "Отправление" -->
      <div class="col-md-6">
        <h2>Отправление</h2>
        <div class="d-flex mb-2">
          <div class="me-2">
            <label>Сортировать по времени:</label>
            <select class="form-select" [(ngModel)]="depSortOrder">
              <option value="asc">По возрастанию</option>
              <option value="desc">По убыванию</option>
            </select>
          </div>
          <div>
            <label>Фильтр по статусу:</label>
            <select class="form-select" [(ngModel)]="depStatusFilter">
              <option *ngFor="let status of statusOptions" [value]="status">{{ status }}</option>
            </select>
          </div>
        </div>
        <div *ngIf="filteredDepartures.length === 0">
          <p>Рейсы не найдены.</p>
        </div>
        <table *ngIf="filteredDepartures.length > 0" class="table table-striped table-hover">
          <thead>
            <tr>
              <th>ID</th>
              <th>Номер рейса</th>
              <th>Время вылета</th>
              <th>Статус</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let flight of filteredDepartures"
                style="cursor: pointer;"
                (click)="navigateToFlight(flight.flightId)">
              <td>{{ flight.flightId }}</td>
              <td>{{ flight.flightNo }}</td>
              <td>{{ flight.scheduledDeparture | date:'short' }}</td>
              <td>{{ flight.status }}</td>
            </tr>
          </tbody>
        </table>
      </div>
  
      <!-- Колонка "Прибытие" -->
      <div class="col-md-6">
        <h2>Прибытие</h2>
        <div class="d-flex mb-2">
          <div class="me-2">
            <label>Сортировать по времени:</label>
            <select class="form-select" [(ngModel)]="arrSortOrder">
              <option value="asc">По возрастанию</option>
              <option value="desc">По убыванию</option>
            </select>
          </div>
          <div>
            <label>Фильтр по статусу:</label>
            <select class="form-select" [(ngModel)]="arrStatusFilter">
              <option *ngFor="let status of statusOptions" [value]="status">{{ status }}</option>
            </select>
          </div>
        </div>
        <div *ngIf="filteredArrivals.length === 0">
          <p>Рейсы не найдены.</p>
        </div>
        <table *ngIf="filteredArrivals.length > 0" class="table table-striped table-hover">
          <thead>
            <tr>
              <th>ID</th>
              <th>Номер рейса</th>
              <th>Время прибытия</th>
              <th>Статус</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let flight of filteredArrivals"
                style="cursor: pointer;"
                (click)="navigateToFlight(flight.flightId)">
              <td>{{ flight.flightId }}</td>
              <td>{{ flight.flightNo }}</td>
              <td>{{ flight.scheduledArrival | date:'short' }}</td>
              <td>{{ flight.status }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
