// src/main/frontend/react/src/components/Footer.jsx
import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';

const Footer = () => {
  return (
    <footer className="bg-dark text-white text-center py-3 mt-4">
      <div className="container">
        &copy; FlyAway Sales 2025
      </div>
    </footer>
  );
};

export default Footer;

// src/main/frontend/angular/src/components/footer/footer.component.ts
import { Component } from '@angular/core';
import 'bootstrap/dist/css/bootstrap.min.css';

@Component({
  selector: 'app-footer',
  standalone: true,
  template: `
    <footer class="bg-dark text-white text-center py-3 mt-4">
      <div class="container">
        &copy; FlyAway Sales 2025
      </div>
    </footer>
  `,
  styles: []
})
export class FooterComponent {}
