// src/main/frontend/react/src/pages/Profile.jsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

const Profile = () => {
  const [user, setUser] = useState(null);
  const [editableUser, setEditableUser] = useState(null);
  const [editing, setEditing] = useState(false);
  const [message, setMessage] = useState('');
  const [tickets, setTickets] = useState([]);

  useEffect(() => {
    fetch('/api/user/info', { credentials: 'include' })
      .then(response => response.json())
      .then(data => {
        setUser(data);
        setEditableUser({ ...data });
      })
      .catch(error => console.error('Ошибка загрузки пользователя:', error));

    fetch('/api/user/tickets', { credentials: 'include' })
      .then(response => response.json())
      .then(data => setTickets(data))
      .catch(error => console.error('Ошибка загрузки билетов:', error));
  }, []);

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('ru-RU', {
      style: 'currency',
      currency: 'RUB',
      minimumFractionDigits: 2
    }).format(amount);
  };

  const handleEditChange = (e) => {
    setEditableUser({ ...editableUser, [e.target.name]: e.target.value });
  };

  const handleSave = async () => {
    try {
      const response = await fetch('/api/user/update', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(editableUser),
        credentials: 'include'
      });

      const result = await response.text();
      if (result === "User updated successfully") {
        setUser({ ...editableUser });
        setEditing(false);
        setMessage("Данные успешно обновлены!");
        setTimeout(() => setMessage(''), 3000);
      } else {
        setMessage("Ошибка обновления данных");
      }
    } catch (error) {
      setMessage("Ошибка обновления данных");
    }
  };

  if (!user) {
    return <p className="text-center">Загрузка...</p>;
  }

  return (
    <>
      <Header />
      <div className="container mt-4 vh-100">
        <h2>Личный кабинет</h2>
        {message && <p className="text-success">{message}</p>}
        
        <div className="card p-3 mb-3">
          {editing ? (
            <>
              <div className="mb-3">
                <label className="form-label">Email:</label>
                <input type="email" name="email" 
                      className="form-control" 
                      value={editableUser.email} 
                      onChange={handleEditChange} 
                      required />
              </div>
              
              <div className="mb-3">
                <label className="form-label">Имя:</label>
                <input type="text" name="firstName" 
                      className="form-control" 
                      value={editableUser.firstName} 
                      onChange={handleEditChange} 
                      required />
              </div>

              <div className="mb-3">
                <label className="form-label">Фамилия:</label>
                <input type="text" name="lastName" 
                      className="form-control" 
                      value={editableUser.lastName} 
                      onChange={handleEditChange} 
                      required />
              </div>

              <div className="mb-3">
                <label className="form-label">Отчество:</label>
                <input type="text" name="patronymic" 
                      className="form-control" 
                      value={editableUser.patronymic || ''} 
                      onChange={handleEditChange} />
              </div>

              <div className="mb-3">
                <label className="form-label">Телефон:</label>
                <input type="text" name="phone" 
                      className="form-control" 
                      value={editableUser.phone} 
                      onChange={handleEditChange} />
              </div>

              <div className="d-grid gap-2 d-md-flex justify-content-md-end">
                <button className="btn btn-success me-md-2" 
                        onClick={handleSave}>
                  Сохранить
                </button>
                <button className="btn btn-secondary" 
                        onClick={() => setEditing(false)}>
                  Отмена
                </button>
              </div>
            </>
          ) : (
            <>
              <h4>{user.firstName} {user.lastName}</h4>
              <p>Email: {user.email}</p>
              {user.patronymic && <p>Отчество: {user.patronymic}</p>}
              <p>Телефон: {user.phone}</p>
              <button className="btn btn-primary" 
                      onClick={() => setEditing(true)}>
                Редактировать профиль
              </button>
            </>
          )}
        </div>

        <h3>История бронирований</h3>
        {tickets.length === 0 ? (
          <p>Нет забронированных билетов.</p>
        ) : (
          <div className="table-responsive">
            <table className="table table-striped table-hover">
              <thead className="thead-dark">
                <tr>
                  <th>Номер билета</th>
                  <th>Номер брони</th>
                  <th>Дата бронирования</th>
                  <th>Сумма</th>
                  <th>Статус</th>
                </tr>
              </thead>
              <tbody>
                {tickets.map(ticket => (
                  <tr key={ticket.ticketNo}>
                    <td>{ticket.ticketNo}</td>
                    <td>{ticket.bookRef}</td>
                    <td>{new Date(ticket.bookDate).toLocaleDateString('ru-RU', {
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit'
                    })}</td>
                    <td>{formatCurrency(ticket.totalAmount)}</td>
                    <td>
                      <span className="badge bg-success">
                        {ticket.status || 'Подтверждено'}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
      <Footer />
    </>
  );
};

export default Profile;

// src/main/frontend/angular/src/pages/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HeaderComponent } from '../../components/header/header.component';
import { FooterComponent } from '../../components/footer/footer.component';
import { UserService } from '../../services/user.service';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [CommonModule, FormsModule, HeaderComponent, FooterComponent],
  templateUrl: './profile.component.html'
})
export class ProfileComponent implements OnInit {
  user: any = null;
  editableUser: any = null;
  editing: boolean = false;
  message: string = '';
  tickets: any[] = [];

  constructor(private userService: UserService) {}

  ngOnInit(): void {
    this.loadUserData();
    this.loadUserTickets();
  }

  loadUserData(): void {
    this.userService.getUserInfo().subscribe({
      next: (data) => {
        this.user = data;
        this.editableUser = { ...data };
      },
      error: (error) => console.error('Ошибка загрузки пользователя:', error)
    });
  }

  loadUserTickets(): void {
    this.userService.getUserTickets().subscribe({
      next: (data) => (this.tickets = data),
      error: (error) => console.error('Ошибка загрузки билетов:', error)
    });
  }

  formatCurrency(amount: number): string {
    return new Intl.NumberFormat('ru-RU', {
      style: 'currency',
      currency: 'RUB',
      minimumFractionDigits: 2
    }).format(amount);
  }

  formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString('ru-RU', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  handleSave(): void {
    this.userService.updateUser(this.editableUser).subscribe({
      next: (result) => {
        if (result === 'User updated successfully') {
          this.user = { ...this.editableUser };
          this.editing = false;
          this.message = 'Данные успешно обновлены!';
          setTimeout(() => (this.message = ''), 3000);
        } else {
          this.message = 'Ошибка обновления данных';
        }
      },
      error: () => {
        this.message = 'Ошибка обновления данных';
      }
    });
  }
}

<app-header></app-header>
<div class="container mt-4 vh-100">
  <h2>Личный кабинет</h2>
  <p *ngIf="message" class="text-success">{{ message }}</p>
  
  <div class="card p-3 mb-3">
    <ng-container *ngIf="editing; else viewProfile">
      <div class="mb-3">
        <label class="form-label">Email:</label>
        <input type="email" name="email" class="form-control" [(ngModel)]="editableUser.email" required>
      </div>
      <div class="mb-3">
        <label class="form-label">Имя:</label>
        <input type="text" name="firstName" class="form-control" [(ngModel)]="editableUser.firstName" required>
      </div>
      <div class="mb-3">
        <label class="form-label">Фамилия:</label>
        <input type="text" name="lastName" class="form-control" [(ngModel)]="editableUser.lastName" required>
      </div>
      <div class="mb-3">
        <label class="form-label">Отчество:</label>
        <input type="text" name="patronymic" class="form-control" [(ngModel)]="editableUser.patronymic">
      </div>
      <div class="mb-3">
        <label class="form-label">Телефон:</label>
        <input type="text" name="phone" class="form-control" [(ngModel)]="editableUser.phone">
      </div>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-success me-md-2" (click)="handleSave()">Сохранить</button>
        <button class="btn btn-secondary" (click)="editing = false">Отмена</button>
      </div>
    </ng-container>
    <ng-template #viewProfile>
      <h4>{{ user.firstName }} {{ user.lastName }}</h4>
      <p>Email: {{ user.email }}</p>
      <p *ngIf="user.patronymic">Отчество: {{ user.patronymic }}</p>
      <p>Телефон: {{ user.phone }}</p>
      <button class="btn btn-primary" (click)="editing = true">Редактировать профиль</button>
    </ng-template>
  </div>

  <h3>История бронирований</h3>
  <ng-container *ngIf="tickets.length === 0; else ticketsTable">
    <p>Нет забронированных билетов.</p>
  </ng-container>
  <ng-template #ticketsTable>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Номер билета</th>
            <th>Номер брони</th>
            <th>Дата бронирования</th>
            <th>Сумма</th>
            <th>Статус</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let ticket of tickets">
            <td>{{ ticket.ticketNo }}</td>
            <td>{{ ticket.bookRef }}</td>
            <td>{{ formatDate(ticket.bookDate) }}</td>
            <td>{{ formatCurrency(ticket.totalAmount) }}</td>
            <td>
              <span class="badge bg-success">
                {{ ticket.status || 'Подтверждено' }}
              </span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </ng-template>
</div>
<app-footer></app-footer>
